### ISSUE TITLE
ECONNRESET when first process with hook is stopped

### ISSUE THREAD

**Issue by miira** [sergeyksv/tinyhook#11]
Hello,
I tried to implement simple signalization between 2 processes. It works, however if the first started process is stopped, the second is getting an exception and terminates:

```
node_modules\tinyhook\node_modules\eventemitter2\lib\eventemitter2.js:290
          throw arguments[1]; // Unhandled 'error' event
          ^

Error: read ECONNRESET
    at exports._errnoException (util.js:874:11)
    at TCP.onread (net.js:544:26)

```

Here is the code for both processes (this one is started as first):

```
var Hook = require("tinyhook").Hook;
var hook = new Hook({name: "test2"});
hook.start();

hook.on("*::*", function () {
    console.log("Got message", arguments);
});

setInterval(function () {
    }, 2000);

```

this is started as second:

```
var Hook = require("tinyhook").Hook;
var hook = new Hook({name: "test"});
hook.start();

var count = 0;

setInterval(function () {
        hook.emit("count", {a:123});
        count++;
    }, 2000);
```

Do you know how this could be handled? Thank you

**Comment by sergeyksv** [comment]
Hooks are organized to star topology. If you use just .start() then the first hook will became main node. But you can control this explicitly by using .listen() for master node and .connect() for child. Child can be restarted without issue, but master node don't. Need to note that only master node is allowed to use .spawn() functionality. In high load projects we use dedicated process for master node that works only as router and supervisor for childs. Need to note that I saw somewhere fully decentralized hook.io alike solution that doesn't have main node.

**Comment by miira** [comment]
So it ("Child can be restarted without issue, but master node don't") means, that whenever master process fails (**it happens), it takes down all processes around? (this is what I saw in simple 2 node setup and was confirmed by you for any topology (star)) It doesn't look like production friendly :/ 
Or is there anything that could prevent it? Thank you for clarification.
